-- Create lookup table for nationalities
-- This provides a standardized list of nationalities for employee forms

CREATE TABLE IF NOT EXISTS public.lookup_nationalities (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  value text NOT NULL,
  CONSTRAINT lookup_nationalities_pkey PRIMARY KEY (id),
  CONSTRAINT lookup_nationalities_value_key UNIQUE (value)
) TABLESPACE pg_default;

-- Enable RLS
ALTER TABLE public.lookup_nationalities ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users to read nationalities
CREATE POLICY "Allow authenticated users to read nationalities"
  ON public.lookup_nationalities
  FOR SELECT
  TO authenticated
  USING (true);

-- Insert all nationalities
INSERT INTO public.lookup_nationalities (value) VALUES
('British'), ('Unknown'), ('Afghan'), ('Alander'), ('Albanian'),
('Algerian'), ('American'), ('American Samoan'), ('Andorran'), ('Angolan'),
('Anguillan'), ('Antiguan'), ('Argentine'), ('Armenian'), ('Aruban'),
('Australian'), ('Austrian'), ('Azerbaijani'), ('Bahamian'), ('Bahraini'),
('Bangladeshi'), ('Barbadian'), ('Basotho'), ('Batswana'), ('Belarusian'),
('Belgian'), ('Belizean'), ('Beninese'), ('Bermudan'), ('Bhutanese'),
('Bolivian'), ('Bosnian'), ('Brazilian'), ('British Virgin Islan'), ('Bruneian'),
('Bulgarian'), ('Burkinabe'), ('Burmese'), ('Burundian'), ('Cambodian'),
('Cameroonian'), ('Canadian'), ('Cape Verdean'), ('Caymanian'), ('Central African'),
('Chadian'), ('Chilean'), ('Chinese'), ('Christmas Islander'), ('Cocos Islander'),
('Colombian'), ('Comoran'), ('Congolese'), ('Cook Islander'), ('Costa Rican'),
('Croatian'), ('Cuban'), ('Cypriot'), ('Czech'), ('Danish'),
('Djiboutian'), ('Dominican'), ('Dominican Republican'), ('Dutch'), ('Dutch Antillean'),
('Ecuadorian'), ('Egyptian'), ('Emirian'), ('Equatorial Guinean'), ('Eritrean'),
('Estonian'), ('Ethiopian'), ('Falkland Islander'), ('Faroese'), ('Fijian'),
('Filipino'), ('Finnish'), ('French'), ('French Guianese'), ('French Polynesian'),
('Gabonese'), ('Gambian'), ('Georgian'), ('German'), ('Ghanaian'),
('Gibraltarian'), ('Greek'), ('Greenlander'), ('Grenadian'), ('Guadeloupian'),
('Guamanian'), ('Guatamalan'), ('Guinea-Bissauan'), ('Guinean'), ('Guyanese'),
('Haitian'), ('HK Chinese'), ('Honduran'), ('Hungarian'), ('Icelander'),
('I-Kiribati'), ('Indian'), ('Indonesian'), ('Iranian'), ('Iraqi'),
('Irish'), ('Israeli'), ('Italian'), ('Ivorian'), ('Jamaican'),
('Japanese'), ('Jordanian'), ('Kazakhstani'), ('Kenyan'), ('Kuwaiti'),
('Kyrgyz'), ('Laotian'), ('Latvian'), ('Lebanese'), ('Liberian'),
('Libyan'), ('Liechtensteiner'), ('Lithuanian'), ('Luxembourger'), ('Macanese'),
('Macedonian'), ('Madagascan'), ('Mahorais'), ('Malawian'), ('Malaysian'),
('Maldivian'), ('Malian'), ('Maltese'), ('Marshall Islander'), ('Martiniquais'),
('Mauritanian'), ('Mauritian'), ('Mexican'), ('Micronesian'), ('Moldovan'),
('Monegasque'), ('Mongolian'), ('Montenegran'), ('Montserratian'), ('Moroccan'),
('Mozambican'), ('Namibian'), ('Nauruan'), ('Nepalese'), ('Nevisian'),
('New Caledonian'), ('New Zealander'), ('Nicaraguan'), ('Nigerian'), ('Nigerien'),
('Niuean'), ('Ni-Vanuatu'), ('Norfolk Islander'), ('North Korean'), ('Northern Mariana Isl'),
('Norwegian'), ('Omani'), ('Pakistani'), ('Palauan'), ('Palestinian'),
('Panamanian'), ('Papua New Guinean'), ('Paraguayan'), ('Peruvian'), ('Pitcairn Islander'),
('Polish'), ('Portuguese'), ('Puerto Rican'), ('Qatari'), ('Reunionese'),
('Romanian'), ('Russian'), ('Rwandan'), ('Sahrawi'), ('Saint Helenian'),
('Saint Lucian'), ('Salvadoran'), ('Sammarinese'), ('Samoan'), ('Sao Tomean'),
('Saudi Arabian'), ('Senegalese'), ('Serbia Montenegran'), ('Serbian'), ('Seychelloise'),
('Sierra Leonean'), ('Singaporean'), ('Slovak'), ('Slovene'), ('Solomon Islander'),
('Somalian'), ('South African'), ('South Korean'), ('Spanish'), ('Sri Lankan'),
('Sudanese'), ('Surinamese'), ('Swazi'), ('Swedish'), ('Swiss'),
('Syrian'), ('Taiwan Chinese'), ('Tajik'), ('Tanzanian'), ('Thai'),
('Timorese'), ('Togolese'), ('Tokelauan'), ('Tongan'), ('Trinidadian'),
('Tunisian'), ('Turkish'), ('Turkmen'), ('Turks and Caicos Isl'), ('Tuvaluan'),
('Ugandan'), ('Ukrainian'), ('Uruguayan'), ('Uzbek'), ('Venezuelan'),
('Vietnamese'), ('Vincentian'), ('Virgin Islander'), ('Wallis and Fortuna I'), ('Yemeni'),
('Zairian'), ('Zambian'), ('Zimbabwean')
ON CONFLICT (value) DO NOTHING;

-- Add comment
COMMENT ON TABLE public.lookup_nationalities IS 'Lookup table for standardized nationality values used in employee forms';
